### ISSUE TITLE
Bilderkennung

### ISSUE THREAD

**Issue by schroedp** [schroedp/ScannerForMultiplePictures#4]
Möglichkeit finden, mehrere Bilder in einem Bild zu erkennen.
mögliche Bibliothek: opencv

**Comment by jonpetersathan** [comment]
- [x] OpenCV zum laufen bringen
- [x] Beispiel Bilder erstellen
- [x] Corner detection erstellen
- [x] Bilder einlesen
- [x] Rectangle Detection testen

**Comment by RoodeyMental** [comment]
![out](https://user-images.githubusercontent.com/43878858/83275101-00af1d80-a1cf-11ea-9e2f-29301cdc7afa.png)

**Comment by jonpetersathan** [comment]
Done with last merge
